netSkope/docker-registry-ui

- src/components/catalog/catalog-element.riot
- src/components/catalog/renovate-replacements-v2.json
With these changes we will be able to identify and mark images as deprecated/non deprecated in docker registry UI. For details - [Link](https://netskope.atlassian.net/browse/EP-40356)
We have added json file which will contain replacement records. 
We have added conditional statements to checkImage method to check whether to mark image as deprecated or not.
Testing -
Did test this locally for both (deprecated and non deprecated cases) 
PFA
> EP-42371: Code changes to identify and mark images as deprecated

- package.json
- src/components/catalog/catalog-element.riot
- src/components/tag-list/tag-list.riot
With these changes we will be able to identify and mark images as deprecated/non deprecated in docker registry UI inside Image details page. We've enabled a mechanism where deprecated records will be cached and reused in subsequent Image details page.
For details - [Link](https://netskope.atlassian.net/browse/EP-43621)
Had to make changes in code submitted by [PR](https://github.com/netSkope/docker-registry-ui/pull/10) to cache the json data for further consumption.
We have added logic to checkImage method to check whether image is deprecated or not.
Testing -
Did test this locally for both (deprecated and non deprecated cases)
> EP-43621: Code to add deprecated icon inside image details

- src/components/catalog/catalog-element.riot
- src/components/tag-list/tag-list.riot
- src/style.scss
With these changes we will be able to identify new location for deprecated images in docker registry UI inside Image details page. This needed fetching of values for individual keys with respective values from renovate-json file, so we had to make changes to the data structure.
For details - [Link](https://netskope.atlassian.net/browse/EP-43715)
This needed fetching of values for individual keys with respective values from renovate-json file, so we had to make changes to the data structure.
Added method to fetch new location info, based on already cached response (from renovate-json file)
Testing -
Did test this locally for both (deprecated and non deprecated cases)
> EP-43621: Code to show location info for deprecated images

- src/components/docker-registry-ui.riot
These changes will provide home redirection on all webpages of netskope docker registry UI . For details - [Link](https://netskope.atlassian.net/browse/EP-44755)
html redirections and css modifications
Testing -
Tested locally, No regressions found. DOcker registry UI text is clickable on all webpages. 
PFA -
> EP-44755: Code changes to add home hyperlink to all webpages

- src/components/catalog/catalog.riot
Currently docker registry UI have some deprecated images, we want those images to excluded when we count for the total number of images on the product home page. 
We also wanted to keep total number of images, so we had to provide user with an option to click the checkbox to exclude number of deprecated images from the total image number.
<Please Note> We get the number of deprecated images after we get the json file and do the processing to find out which out of those are deprecated ones. So its a bit time consuming, We cant stop page loading till that time, so we adopted the [eventual consistency](https://en.wikipedia.org/wiki/Eventual_consistency)  for data loading on UI. RIOT supports it. 
For details - [Link](https://netskope.atlassian.net/browse/EP-44998) …
> EP-44998: Code changes to add checkbox functionality to exclude number of deprecated images from total number of images

- src/components/catalog/catalog.riot
Currently docker registry UI have some deprecated images, we want those images to excluded when we count for the total number of images on the product home page. 
When user clicks to exclude images individual image count (non-deprecated image count) should also be updated at the same time, user should not be able to see the set of deprecated images.
For details - [Link](https://netskope.atlassian.net/browse/EP-46493)
We have modified catalog.riot code, 
javascript changes to perform the actions/ calculations after selection/de-selection of the checkbox
Testing -
PFA, images of local testing
> EP-46493: Code changes to hide deprecated images when we click exclude deprecated images checkbox

- src/components/tag-history/tag-history.riot
Currently in docker registry UI on tag history page we are missing icons for both ENV and labels section, we are trying to add those thru. this PR.
For details - [Link](https://netskope.atlassian.net/browse/EP-47229)
Minor HTML/js code changes
Testing -
PFA, the image of local testing. 
Updates - 
Review suggestion - Fix vertical alignment mismatch between icon and the text.
> EP-47229: Code changes to add icons to both env and labels sections

- src/components/tag-history/image-label.riot
Currently in docker registry UI on tag history page we see some labels view is broken. PFA. 
This was happening for ns-service/mtail-current. 
We've added more debug details here -  [Link](https://netskope.atlassian.net/browse/EP-48023)
js code changes to remove double quotes from beginning and end of the string value label.
Testing -
PFA, the image of local testing.
> EP-48023: Code changes to fix broken labels view on tag history page

- src/components/tag-history/tag-history.riot
EP-48316: Code changes to download report of given image and present it on ui
We have added a mechanism thru. which we trivy scan ep-pokeball images, we generate reports of the same and upload it to artifactory location. We have already created API to access scan report of a given image [Refer]([EP-48314](https://netskope.atlassian.net/browse/EP-48314)) 
This PR intends to invoke API and fetch + parse json report and presents in on UI. 
@ns-ggeorgiev  mentioned for this PR, we will present report data as is. Based on discussion with @ns-snandan  I've removed some (not needed) fields of a given vulnerability to make report more focussed and avoid unnecessary details.
For details - [Link](https://netskope.atlassian.net/browse/EP-48316)
We have …
> EP-48316: Code changes to download report of given image and present it on ui

- src/components/help.riot
FAQ's Routed to: https://netskope.atlassian.net/wiki/spaces/PE/pages/4610556807/Guidelines+for+creating+ep-pokeball+images
> EP-48257: added FAQ's page.

- src/components/tag-history/tag-history.riot
Why this change was made - 
There are few changes that we did recently, it caused change in structure for vulnerability report. 
We need to change our ways we used to fetch list of vulnerabilities from the report. 
What is the change - 
change in tag-history.riot file 
Testing -
> EP-48885: Code changes to fix broken tag history vulnerability report

- src/components/tag-history/tag-history.riot
EP-48872: Code changes related to presentation of vulnerability report on docker registry ui
We have vulnerability report information, which we now want to present to docker registry ui users in similar way the dockerhub website does. This PR addresses the same. 
This PR to be considered for basic structuring of vulnerability report information on tag history page. Please add review comments if you think, we are missing anything. 
**Note** - There are going to be few more enhancements on top of this PR to make UI better in terms of representation of vulnerability info. 
For e.g. https://netskope.atlassian.net/browse/EP-48970.
Feel free to add such suggestions/improvements on this PR or on ticket (EP-48872) 
html/js/css changes in …
> EP-48872: Code changes related to presentation of vulnerability report on docker registry ui

- src/components/tag-history/tag-history.riot
We have vulnerability report information, which we now want to present to docker registry ui - tag history page. We want our end users to be aware of last updated date information for the respective image vulnerability scan report.
This PR addresses the same. 
There are few additional suggestions from @ns-ggeorgiev  -
1. For the images where we don't have report or somehow we could not fetch report, we should not show (last updated date) information.
2. Date presentation should have month in letters rather than in digital format.  
For more info and tracking - https://netskope.atlassian.net/browse/EP-48760
html/js/css changes in tag-history.riot file
Testing -
PFA, screenshot of local testing .
1. For images with downloadable report. 
2. For …
> EP-48760: Code changes to show vulnerability scan time info

- src/components/tag-history/tag-history.riot
We have vulnerability report information, which we now want to present to docker registry ui - tag history page. We want to present vulnerability information (category wise) and color coded. I.e. separate color codes need to be used per vulnerability category. For exact colors to be consumed, please refer dockerhub website. 
This PR addresses the same.
Changes we did - 
1. Color coding specific to vulnerability category 
2. Rectangle features same as that of dockerhub website
3. Background color change for expanded rows just to let user feel difference between expanded and original table rows (Suggestion from @George Georgiev )
4. If user hover over particular vulnerability rectangle , we show what category it is.
For more info and tracking - …
> EP-48970: Code changes to color code vulnerability info as per severity and other improvements

- src/components/tag-history/tag-history.riot
Following code implements some of the suggestions @ns-ggeorgiev provided - 
1. Fix vertical alignement for digits inside rectangles. 
2. Dockerhub color codes should not be followed, @George Georgiev provided color codes should be implemented.
#FFD1B3
#FFB380
#FF944D
#FF751A
#E65C00
This PR addresses the same.
For more info and tracking - https://netskope.atlassian.net/browse/EP-49421
What have we changed -
Html/CSS/JS changes in tag-history.riot
Testing -
PFA, Images of local testing.
> EP-49421: Docker registry ui improvements

- src/components/tag-history/tag-history.riot
.Why this change was made -
We have vulnerability report information, which we now want to present to docker registry ui - tag history page. 
There are following 2 cases -
1. When report itself is not available for given image and tag.
2. When image is vulnerability free
Currently in both cases, we show empty vulnerability report table. We need a way to bifurcate the same and make our users aware of the individual case.
This PR addresses the same.
For more info and tracking - https://netskope.atlassian.net/browse/EP-49053
What have we changed -
Html/CSS/JS changes in tag-history.riot
Testing - 
PFA, Images of local testing.
Happy path testing (when report data is present) -
> EP-49053: Code changes to show appropriate report and text in no report or zero vulnerability cases

- src/components/tag-history/tag-history.riot
When an image does not have any vulnerability typically vulnerability attribute itself will be missing from the resulting json. We missed this case, and continued to show empty table instead of vulnerability free image and respective text message. This PR addresses the same. 
For more info and tracking - https://netskope.atlassian.net/browse/EP-49643
js changes in tag-history.riot file
Testing -
PFA, screenshot of local testing .
> EP-49643: Fix for images with 0 vulnerabilities

- src/components/tag-history/tag-history.riot
We have explored multiple options to represent vulnerability info. the same are mentioned here - [EP-49421](https://netskope.atlassian.net/browse/EP-49421)
For now we want to go ahead with the option which we think looks better.
For more info and tracking - https://netskope.atlassian.net/browse/EP-49421
js changes in tag-history.riot file
Testing -
PFA, screenshot of local testing .
[EP-49421]: https://netskope.atlassian.net/browse/EP-49421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EP-49712: Code changes to represent vulnerability info

- src/components/tag-history/tag-history.riot
We want to remove DOCKERFILE button on tag-history page, as it does not have any functionality associated with it as of now. This PR addresses the same. 
For more info and tracking - https://netskope.atlassian.net/browse/EP-49701
html changes in tag-history.riot file
Testing -
PFA, screenshot of local testing , No dockerfile button on the top - right side.
> EP-49701: Code changes to remove dockerfile button

- src/components/tag-history/tag-history.riot
- src/components/tag-list/tag-table.riot
- src/components/utility/rectangle-styles.css
- src/components/utility/utility.js
We are furnishing package wise vulnerability report on tag-history page. We need to show its overview on tag-list so user gets glimpse of it and can make quick decision. This code addresses the same. 
We are also making code more object oriented so it could be reused from multiple places. 
For more info and tracking - https://netskope.atlassian.net/browse/EP-49771
html/js/css changes in tag-history.riot, tag-table.riot.
Added 2 new files - src/components/utility/rectangle-styles.css, src/components/utility/utility.js
Testing -
PFA, screenshot of local testing 
Test 1 - Image with tag having vulnerabilities 
Test 2 - Image with tag having no vulnerability report
Test 3 - Image with multiple tags , few having vulnerabilities, few without …
> EP-49771: Code changes to bring vulnerability overview to tag list page

- src/components/catalog/catalog-element.riot
- src/components/catalog/catalog.riot
- src/components/docker-registry-ui.riot
- src/components/tag-list/tag-list.riot
As we new repos tool, service. our deprecated logic worked fine with org-base-release-docker repo. Now it is showing incorrect due to checking name against org-base-release-docker instead of org-tool-release-docker repo.
Currently if you see golang-alpine-current is deprecated in ns-builder org-base-release docker
Now it is corrected
> EP-49931: deprecated logic is corrected.

- src/components/utility/utility.js
We are changing background colors for the rectangles (representing vulnerability information) .. So in case where we have 0 vulnerability of the given severity type, we will use background colors ( ['#7a7a7a', '#929292', '#a9a9a9', '#c1c1c1', '#dadada'] ) from left to right. 
Just to get idea of current scheme of things , please refer [link](https://ep-pokeball.netskope.io/#!/taglist/ns-ep/ubuntu2004-current)
JS code changes in src/components/utility/utility.js
Testing -
PFA, screenshot of local testing.
[
](url)
> EP-49712: Code changes to change background colors to represent vulnerability information

- src/components/tag-history/tag-history.riot
- src/components/tag-list/tag-table.riot
Earlier with tool repo we are showing vulnerabilities col and report section
After this code we are hiding vulnerabilities for tool-repo
> EP-50869: hiding vulnerabilities tab and vulnerability report in history section in tool repo.

- src/components/docker-registry-ui.riot
added button as per the requirement.
> 1. if it is "Base" repo UI will display like this
> 
>     <img width="1722" alt="Screenshot 2024-10-07 at 11 12 42 AM" src="https://github.com/user-attachments/assets/291776b6-e41d-461d-ab6a-13370a124bdc">
> 2. if it is "Service" repo UI will display like this
>
>  
> 3. if it is "Tool"  repo UI will display like this
>
>
> EP-51884: added buttons to switch UI.

- src/components/tag-list/tag-table.riot
These changes are to add efficiency data on tag list page . Backend was already prepared by Suhal. Also call to fetch data from backend was also there in utility/dive. 
We made some changes into riot framework files - when we fetch dive report data (async/) and addditional css related changes. 
By mistake as the main branch netskope@main was not protected from push. Commits got pushed directly, this is reference PR created to trigger GH workflows to deploy changes to production and also get changes referenced here.
commit/acabad4b8fabb1837345a2e186793cc85d344fc3 ( [link](https://github.com/netSkope/docker-registry-ui/commit/acabad4b8fabb1837345a2e186793cc85d344fc3) )
commit/3d4dcc132e3b592fd0702a53962f795988039f34 ( …
> EP-57525: Code changes to add efficiency column to tag list page

- src/components/tag-list/tag-table.riot
In one of our previous work, we did resizing of columns that are part of tag-list table. There multiple reasons because of which tables go beyond webpage window, thus requiring user to use horizontal scroll bar. 
i) Dynamic Content Injection: During the loading phase, if the content (like tags, size, or vulnerabilities) is still being fetched, columns might temporarily grow larger than expected, especially if the content doesn't fit within the predefined width.
ii) Asynchronous Data Loading: The table may be trying to adjust columns as it receives data, especially if some columns (like the Vulnerabilities or Efficiency columns) are populated after the table has initially loaded.
iii) Column Visibility: If the columns are changing their visibility (display: none …
> EP-57571: Code changes related to fix table getting stretched horizontally while loading is in progress
